language:
  - ruby

rvm:
  - 2.5.5
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3

gemfile:
  - gemfiles/rails6.0.0.gemfile
  - gemfiles/rails6.0.1.gemfile
  - gemfiles/rails6.0.2.gemfile
  - gemfiles/rails6.0.2.1.gemfile

install:
  - "gem install bundler"
  - "travis_retry bundle install"

before_script:

script:
  - "bundle exec rake"

branches:
  only:
    - master
