language:
  - ruby

rvm:
  - 2.2.2
  - 2.2.3
  - 2.3.0

gemfile:
  - gemfiles/rails4.1.15.gemfile
  - gemfiles/rails4.1.16.gemfile
  - gemfiles/rails4.2.7.gemfile
  - gemfiles/rails4.2.7.1.gemfile
  - gemfiles/rails5.0.0.gemfile
  - gemfiles/rails5.0.0.1.gemfile

install:
  - "gem install bundler"
  - "travis_retry bundle install"

before_script:

script:
  - "bundle exec rake"

branches:
  only:
    - master
