language:
  - ruby

rvm:
  - 2.0.0
  - 2.1.3
  - 2.2.1
  - 2.2.3

gemfile:
  - gemfiles/rails4.1.13.gemfile
  - gemfiles/rails4.1.14.gemfile
  - gemfiles/rails4.2.4.gemfile
  - gemfiles/rails4.2.5.gemfile

install:
  - "gem install bundler"
  - "travis_retry bundle install"

before_script:

script:
  - "bundle exec rake"

branches:
  only:
    - master
