language:
  - ruby

rvm:
  - 2.0.0
  - 2.1.3
  - 2.2.1

gemfile:
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile

install:
  - "gem install bundler"
  - "travis_retry bundle install"

before_script:

script:
  - "bundle exec rake"

branches:
  only:
    - master
